language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-android-m2repository
    - extra-google-android-support
    - android-$ANDROID_API_LEVEL
  licenses:
    - '.+'